# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect_detects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('detect_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Suspect_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('threat', models.IntegerField(blank=True, null=True)),
                ('last_found', models.TimeField()),
            ],
        ),
    ]
