# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect_names',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
    ]
