# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-01 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0002_auto_20210425_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect_detects',
            name='detect_location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
