# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0003_suspect_detects_detect_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect_names',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suspect_images/'),
        ),
    ]
