# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0004_suspect_names_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect_names',
            name='last_pic',
            field=models.ImageField(blank=True, null=True, upload_to='detect_images/'),
        ),
    ]
