# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-01 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0005_suspect_names_last_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect_detects',
            name='detect_pic',
            field=models.ImageField(blank=True, null=True, upload_to='all_images/'),
        ),
    ]
