# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0006_suspect_detects_detect_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect_names',
            name='image',
            field=models.ImageField(blank=True, default='default/default_pic.jpg', null=True, upload_to='suspect_images/'),
        ),
        migrations.AlterField(
            model_name='suspect_names',
            name='last_pic',
            field=models.ImageField(blank=True, default='default/default_pic.jpg', null=True, upload_to='detect_images/'),
        ),
    ]
