# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-13 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0008_auto_20210508_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face_detects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_img', models.ImageField(blank=True, default='default/default_pic.jpg', null=True, upload_to='face_images/', verbose_name='img')),
            ],
        ),
    ]
