# Generated by Django 3.2 on 2021-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0009_face_detects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect_recognised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('detect_time', models.TimeField()),
                ('detect_location', models.CharField(max_length=100)),
                ('detect_pic', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Face_detects',
        ),
        migrations.AlterField(
            model_name='suspect_detects',
            name='detect_pic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suspect_detects',
            name='sid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suspect_names',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suspect_names',
            name='last_pic',
            field=models.CharField(max_length=100),
        ),
    ]
