# Generated by Django 3.2.3 on 2021-05-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0010_auto_20210529_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suspect_names',
            new_name='Suspect_profiles',
        ),
        migrations.DeleteModel(
            name='Suspect_detects',
        ),
    ]
