# Generated by Django 3.2.3 on 2021-05-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0013_alter_suspect_recognised_detect_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect_profiles',
            name='last_found',
        ),
        migrations.AddField(
            model_name='suspect_profiles',
            name='detect_time',
            field=models.CharField(default='2021-05-31 21:06:15', help_text='Format: YYYY-MM-DD HH:MM:SS', max_length=100),
        ),
        migrations.AlterField(
            model_name='suspect_recognised',
            name='detect_time',
            field=models.CharField(default='2021-05-31 21:06:15', help_text='Format: YYYY-MM-DD HH:MM:SS', max_length=100),
        ),
    ]
