# Generated by Django 3.2.3 on 2021-05-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0015_auto_20210531_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect_profiles',
            name='detect_time',
        ),
        migrations.AddField(
            model_name='suspect_profiles',
            name='last_found',
            field=models.CharField(default='2021-05-31 21:36:14', help_text='Format: YYYY-MM-DD HH:MM:SS', max_length=100),
        ),
        migrations.AlterField(
            model_name='suspect_recognised',
            name='detect_time',
            field=models.CharField(default='2021-05-31 21:36:14', help_text='Format: YYYY-MM-DD HH:MM:SS', max_length=100),
        ),
    ]
